#151 Wire up authentication module
Azure/benchpress pull request #158
Opened 2023-02-14 22:50 UTC by ozboms

Adding authentication `Connect-Account` to each Get-Resource.
Added additional information about using environment variables in the `getting_started.md`.

2023-02-14 22:56 UTC, ozboms commented
unit tests worked locally but failing on agent; looking into it

2023-02-15 00:07 UTC, msha1026 commented on examples/ResourceGroup.Tests.ps1
> +    $exists = Get-AzBPResourceGroupExist($rgName)
Can this function call also be changed to use named parameters?
```suggestion
    $exists = Get-AzBPResourceGroupExist -ResourceGroupName $rgName
```

2023-02-15 00:08 UTC, msha1026 approved these changes

2023-02-15 00:23 UTC, marclerwick requested changes

2023-02-15 00:23 UTC, marclerwick commented on docs/getting_started.md
> +    $Env:AZ_ENCRYPTED_PASSWORD="<sample-id>"
```suggestion
    $Env:AZ_ENCRYPTED_PASSWORD="<sample-encrypted-password>"
```

2023-02-15 00:38 UTC, marclerwick approved these changes

2023-02-15 00:44 UTC, merged