Resolve Inconsistencies Pt. 1
Azure/benchpress pull request #288
Opened 2023-03-29 22:55 UTC by msha1026

2023-03-30 18:44 UTC, marclerwick requested changes

2023-03-30 18:44 UTC, marclerwick commented on examples/CosmosDB/CosmosDB.Tests.ps1
> +  It "Should contain a Sql Cosmos DB Account named $sqlAccountName - Confirm-AzBPResource" {
Fully capitalize `SQL`

2023-03-30 18:44 UTC, marclerwick commented on examples/SqlDatabase/SqlDatabase.Tests.ps1
> +  It "Should contain a Sql Database named $databaseName - Confirm-AzBPResource" {
Fully capitalize `SQL`

2023-04-04 16:20 UTC, ozboms commented on examples/ResourceGroup/ResourceGroup_Example.md
Could you add a location parameter here?

```suggestion
`westus3` -> `your-resource-group-location`
```

2023-04-04 16:23 UTC, ozboms commented on examples/SqlDatabase/SqlDatabase.Tests.ps1
> +  It 'Should not contain a SQL Database with the given name' {
```suggestion
  It 'Should not contain a SQL Database named $noDatabaseName' {
```

2023-04-04 16:24 UTC, ozboms commented on examples/SqlServer/SqlServer.Tests.ps1
> +  It 'Should not contain a SQL Server with the given name' {
```suggestion
  It 'Should not contain a SQL Server named $noServerName' {
```

2023-04-04 19:59 UTC, quigg-caroline approved these changes

2023-04-04 20:48 UTC, marclerwick approved these changes

2023-04-04 20:52 UTC, merged