applying naming conventions
Azure/benchpress pull request #98
Opened 2023-01-13 22:54 UTC by polatengin

closes #32

as discussed in the design session,

`AzBP` prefix added to all helper cmdlets
`Exists` keyword replaced with `Exist` keyword

also, to be compliant with Powershell naming guidelines, I converted camel casing to pascal casing for cmdlet parameters

PS : noticed that I missed adding couple of nested modules and their functions list in BenchPress.Azure module. fixed that, too.

2023-01-13 22:58 UTC, msha1026 commented on BenchPress/Helpers/Azure/AKSCluster.psm1
> +function Get-AKSCluster{
Missing "Exist"

2023-01-13 22:59 UTC, msha1026 commented on BenchPress/Helpers/Azure/ActionGroup.psm1
> +function Get-ActionGroup{
Missing "Exist"

2023-01-13 22:59 UTC, msha1026 commented on BenchPress/Helpers/Azure/ActionGroup.psm1
> +Export-ModuleMember -Function Get-ActionGroup, Get-ActionGroupExists
Change Exists -> Exist

2023-01-13 23:00 UTC, msha1026 commented on BenchPress/Helpers/Azure/ContainerRegistry.psm1
> +function Get-ContainerRegistry{
Missing "Exist"

2023-01-13 23:00 UTC, msha1026 commented on BenchPress/Helpers/Azure/ContainerRegistry.psm1
> +Export-ModuleMember -Function Get-ContainerRegistry, Get-ContainerRegistryExists
Exists -> Exist

2023-01-13 23:00 UTC, msha1026 commented on BenchPress/Helpers/Azure/KeyVault.psm1
> +function Get-KeyVault{
Missing "Exist"

2023-01-13 23:02 UTC, msha1026 commented on BenchPress/Helpers/Azure/KeyVault.psm1
> +  Get-KeyVault-Name "kvbenchpresstest" -ResourceGroupName "rgbenchpresstest"
Missing space between KeyVault and -Name

2023-01-13 23:03 UTC, msha1026 commented on BenchPress/Helpers/Azure/ContainerRegistry.psm1
> +  Get-ContainerRegistry-Name "benchpresstest" -ResourceGroupName "rgbenchpresstest"
Missing space between Get-ContainerRegistry and -Name

2023-01-13 23:04 UTC, msha1026 commented on BenchPress/Helpers/Azure/ActionGroup.psm1
> +  Get-ActionGroup-ActionGroupName "benchpresstest" -ResourceGroupName "rgbenchpresstest"
Missing space between `ActionGroup` and `-ActionGroupName`

2023-01-13 23:04 UTC, msha1026 commented on BenchPress/Helpers/Azure/AKSCluster.psm1
> +  Get-AKSCluster -ActionGroupName "benchpresstest" -ResourceGroupName "rgbenchpresstest"
`-ActionGroupName` -> `AKSName`

2023-01-13 23:07 UTC, msha1026 commented on BenchPress/Helpers/Azure/KeyVault.psm1
> +  Get-KeyVaultSecret-Name "samplesecret" -KeyVaultName "kvbenchpresstest"
`KeyVaultSecret` -> `KeyVaultSecretExist` and missing space before `-Name`

2023-01-13 23:08 UTC, msha1026 commented on BenchPress/Helpers/Azure/KeyVault.psm1
> +function Get-KeyVaultSecret{
Missing `Exist`

2023-01-13 23:08 UTC, msha1026 commented on BenchPress/Helpers/Azure/KeyVault.psm1
> +  Get-KeyVaultKey-Name "samplekey" -KeyVaultName "kvbenchpresstest"
`KeyVaultKey` -> `KeyVaultKeyExist` and missing space before -Name

2023-01-13 23:09 UTC, msha1026 commented on BenchPress/Helpers/Azure/KeyVault.psm1
> +function Get-KeyVaultKey{
Missing `Exist`

2023-01-13 23:15 UTC, msha1026 requested changes

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/KeyVault.psm1
> +  Get-KeyVaultCertificate-Name "samplecertificate" -KeyVaultName "kvbenchpresstest"
`KeyVaultCertificate` -> `KeyVaultCertificateExist` and missing space before `-Name`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/ResourceGroup.psm1
> +  Get-ResourceGroup-ResourceGroupName "rgbenchpresstest"
`ResourceGroup` -> `ResourceGroupExist` and missing space before `-ResourceGroupName`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/ResourceGroup.psm1
> +Export-ModuleMember -Function Get-ResourceGroup, Get-ResourceGroupExists
`Exists` -> `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/KeyVault.psm1
Edit exported cmdlets to change `Exists` -> `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/ServicePlan.psm1
> +  Get-AppServicePlan-AppServicePlanName "appsvcbenchpresstest" -ResourceGroupName "rgbenchpresstest"
`AppServicePlan` -> `AppServicePlanExist` and missing space before `-AppServicePlanName`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/ServicePlan.psm1
> +function Get-AppServicePlan{
Missing `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/ServicePlan.psm1
> +Export-ModuleMember -Function Get-AppServicePlan, Get-AppServicePlanExists
`Exists` -> `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/SqlDatabase.psm1
> +function Get-SqlDatabase{
Missing `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/SqlDatabase.psm1
> +Export-ModuleMember -Function Get-SqlDatabase, Get-SqlDatabaseExists
`Exists` -> `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/SqlServer.psm1
> +function Get-SqlServer{
Missing `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/SqlServer.psm1
> +Export-ModuleMember -Function Get-SqlServer, Get-SqlServerExists
`Exists` -> `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/VirtualMachine.psm1
> +function Get-VirtualMachine{
Missing `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/VirtualMachine.psm1
> +Export-ModuleMember -Function Get-VirtualMachine, Get-VirtualMachineExists
`Exists` -> `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/WebApp.psm1
> +function Get-WebApp{
Missing `Exist`

2023-01-13 23:15 UTC, msha1026 commented on BenchPress/Helpers/Azure/WebApp.psm1
> +Export-ModuleMember -Function Get-WebApp, Get-WebAppExists
`Exists` -> `Exist`

2023-01-13 23:57 UTC, polatengin commented on BenchPress/Helpers/Azure/AKSCluster.psm1
> +function Get-AKSCluster{
👍

2023-01-13 23:57 UTC, polatengin commented on BenchPress/Helpers/Azure/ActionGroup.psm1
> +function Get-ActionGroup{
👍

2023-01-13 23:57 UTC, polatengin commented on BenchPress/Helpers/Azure/ActionGroup.psm1
> +Export-ModuleMember -Function Get-ActionGroup, Get-ActionGroupExists
👍

2023-01-13 23:57 UTC, polatengin commented on BenchPress/Helpers/Azure/ContainerRegistry.psm1
> +function Get-ContainerRegistry{
👍

2023-01-13 23:57 UTC, polatengin commented on BenchPress/Helpers/Azure/KeyVault.psm1
> +function Get-KeyVault{
👍

2023-01-13 23:57 UTC, polatengin commented on BenchPress/Helpers/Azure/ContainerRegistry.psm1
> +Export-ModuleMember -Function Get-ContainerRegistry, Get-ContainerRegistryExists
👍

2023-01-14 00:07 UTC, msha1026 approved these changes
These changes will resolve the linting issues. I know we talked about removing Exist functions in general, but that is up to SA and PG. As long as long-term owners are onboard with these naming changes, then I think this is ok to merge!

2023-01-14 00:11 UTC, merged